### ISSUE TITLE
User-can-create-an-entry

### ISSUE THREAD

**Issue by Aiden-Peace300** [Aiden-Peace300/KeyWord-Relief-AJAX#1]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Allows users to type in a definition and see a list of 5 words resembling the definition provided by the user

## 🖼️ Wireframes

USERS CAN CREATE AN ENTRY MOBILE:  
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/0ef70f5a-4054-4368-8ffb-c1b255071d7f)

USERS CAN CREATE AN ENTRY DESKTOP:
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/dd7e0be6-adfd-4a17-9ed7-4a49ca608fc0)

## ✅ Task List
- [x] Create an HTML file called index.html Start off creating the header in the `header` div that corresponds to the [figma ](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0)example(s). 
- [x] Below the header, create the HTML for the form that creates a journal entry in the `data-view="entry-form"` element. This form needs to match the format shown in the example [figma](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0).
- [x] Complete the HTML form using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop usage.
- [x] Make input of the journal entry form `required`.
- [x] Add a `'submit'` event listener to the form element that:
  - [x] prevents the page from refreshing when the form is submitted.
  - [x] stores the form's input values in a new object.
  - [x] assigns an `entryId` property to the new object, taken from the `nextEntryId` property of the data model.
  - [x] increments the `nextEntryId` property of the data model so that if another entry is submitted later, it will receive a different `entryId`.
  - [x] adds the new object to the beginning of the data model's array of entries.
  - [x] resets the input for that entry
  - [x] resets the form.
- [x] In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding entries to the pre-existing data model.
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` before each page reload.
  - [x] each word choosen by the user will become a entry object is receiving an incrementing `entryId` property.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
