### ISSUE TITLE
User-can-view-five-words-matching-their-definition 

### ISSUE THREAD

**Issue by Aiden-Peace300** [Aiden-Peace300/KeyWord-Relief-AJAX#2]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to see a list of 5 words resembling the definition input provided by the user

## 🖼️ Wireframes

USERS CAN CREATE AN ENTRY MOBILE:
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/01d7c1a6-0978-45c3-a6ed-b4df3c1d2937)

USERS CAN CREATE AN ENTRY DESKTOP:
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/5ddc217d-9650-4a40-b038-24ec11c980c6)

## ✅ Task List
- [x] Add an empty unordered list to the div[data-view="list-words-options"] element in the HTML. [figma ](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0)example(s). 
- [x] Create some dummy word entries to the unordered list in the HTML and style them to match the example entries in the [figma ](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0)example(s). Each entry’s content should be in a single li element within the ul element.
- [x] Check that the example entries you just created in the unordered list are responsive for both mobile and desktop screens.
- [x] Create a function named `getMsgData` that will need one parameter which is the user's input 'def' and will return the user's five definition:
  - [x] Connect the chat GPT API with your designated API key. (Chat GPT only accepts POST requests)
  - [x] Set the 'Authorization' header to include the API key
  - [x] Set the 'Content-Type' header to indicate JSON data is being sent
  - [x] Set responseType to accept JSON type values
  - [x] Add an event listener to the xhr object listening for the 'load' event and passing a callback function
	- [x] Loop through the response choices to obtain chat GPT message in response to the user's input
  - [x] an object called "requestData" This is a POST request, so we need to send some type of data to the xhr object
  - [x] Send requestData as a JSON string to the xhr object
- [x] Create a function named `MsgGetCutIntoFivePieces` that will need one parameter which is the data returned by 'getMsgData' and this function will need to return the chat GPT message into 5 numbered parts each assigned to an array called `arrayOfOptions` 
- [x] create a function called `toggleSubmitButton` to ensure that the user will only see the `SAVE WORDS` button after options render to the user
- [x] create a function called `renderOptions` which will generate a DOM tree for each entry in the array, and append that DOM tree to the unordered list. connected to a li(s) to div[data-view="list-words-options"]
    - [x] Create an event listener which listens for each button event. In the callback function for that event, loop through the 'selectableButtons' array and generate an array called `selectedButtons` which will hold all the words that user want to save from the options given to them.
- [x] Remove the example HTML entries from index.html once the user's entries are successfully being appended to the DOM on page load which matches the figma.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
