### ISSUE TITLE
user-can-view-the-words-they-chose-from-the-past

### ISSUE THREAD

**Issue by Aiden-Peace300** [Aiden-Peace300/KeyWord-Relief-AJAX#3]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Allows users to see a list of all the words they ever saved with dates 

## 🖼️ Wireframes

USERS CAN CREATE AN ENTRY MOBILE:
![image](https://github.com/Aiden-Peace300/KeyWord-Relief-AJAX/assets/47370726/bb3db97a-d051-477a-9e94-95605f0250ca)
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/98fd8da8-a28f-43bc-85fc-84294313002a)

USERS CAN CREATE AN ENTRY DESKTOP:
![image](https://github.com/Aiden-Peace300/KeyWord-Relief-AJAX/assets/47370726/c576a1c6-c1c7-4434-abc3-31e47db8e51e)
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/92f300fb-bf0c-4e9b-a9d6-e8b24c0c513b)

## ✅ Task List

- [x] Create an interactive navigation button that will ensure that the user navigates to the appropriate information. That corresponds to the [figma ](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0)example(s). 
   - [x] define a function called `viewSwap` this function's purpose is to switch between views (entry-form and `data-view="nav-links"`)
    - [x] Create a new function named `viewSwap` with a single parameter representing the name of the view to show (the value will be either `”saved-words”` or `”entry-form”`). This function should show the view whose name was provided as an argument, as well as assign the string argument to the `data.view` property so that the currently shown view is tracked in the data model for the application.
    - [x] Add an anchor to the navbar to show the `”saved-words”` view. You will need to create an event handler function that utilizes the `viewSwap` function to show the proper view.
    - [x] Add an anchor to the entries view to show the `entry-form`. It should be styled like a button with the text `NEW`, and must match the [figma ](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0)example(s).
   - [x] add a `click` Listener to the home button and logo button 
   - [x] Adjust styling to fluidly adapt to desktop usage.
- [x] Add an empty unordered list to the `div[data-view="saved-words"]` element in the HTML.
- [x] Create some dummy word entries to the unordered list in the HTML and style them to match the example entries in the [figma ](https://www.figma.com/file/CSVVkiEGFGVYJs4TnfAXp5/KeyWord-relief?type=design&node-id=0-1&mode=design&t=EvuVgvNSppgVC248-0)example(s). Each entry’s content should be in a single `li` element within the `ul` element.
- [x] Check that the example entries you just created in the unordered list are responsive for both mobile and desktop screens.
- [x] Define a function named `renderKeywordList` with a single parameter. The parameter will need to be `selectedButtons` array. The function should generate and return a DOM tree from the `selectedButtons` array each element in that array needs to match the entries you created in the unordered list.
- [x] Create a function called `extractWord` with a single parameter. which will need to ensure that the listed words don't have numbers  attached to them like the user sees when they select an option from `div[data-view="entry-form"]` 
- [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.entries` array and generate a DOM tree for each entry in the array, and append that DOM tree to the unordered list.
  - [x] Clear the input and reset the form
  - [x] Saving the selectedButtons array to localStorage
- [x] Remove the example HTML entries from `index.html` once the user's entries are successfully being appended to the DOM on page load and replace them with a message indicating that no entries have been recorded which matches the figma.
- [x] Update the `submit` callback for the form to do the following:
  - [x] Render a DOM tree for the newly submitted entry object using the `renderKeywordList` function.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
