### ISSUE TITLE
user-can-delete-a-word-from-the-view-past-vocabulary-list

### ISSUE THREAD

**Issue by Aiden-Peace300** [Aiden-Peace300/KeyWord-Relief-AJAX#4]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to see a list of 5 words resembling the definition input provided by the user

## 🖼️ Wireframes

USERS CAN CREATE AN ENTRY MOBILE:
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/a7b12375-ff08-411a-9476-2df6bc5c6174)

USERS CAN CREATE AN ENTRY DESKTOP:
![image](https://github.com/Aiden-Peace300/ajax-project/assets/47370726/abc95fc6-e01a-4c0e-b7a6-f13c3675020c)

## ✅ Task List
- [x] Add a div to index.html which is only visible when an entry is currently being edited.
- [x] Show a confirmation modal when the user clicks **Delete Icon**
- [x] When the user clicks **Cancel**, hide the modal.
- [x] When the user clicks **Confirm**:
  - [x] remove the corresponding entry object from the data model's entry array.
  - [x] remove the entry's `li` element from the DOM.
  - [x] hide the modal.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
